#Requires -Version 7.0
# Regenerates the human-readable follow-up index from the per-entry files' front matter.
# The index is for the user only: agents grep the entry files instead (see the followup skill).
#   pwsh -NoProfile -File fu-index.ps1 [-Dir docs/fu] [-Out docs/follow-ups.md]
# Run from the repo root. Deterministic: same entries, same bytes — no dates, so it never makes a diff on its own.
param(
    [string] $Dir = 'docs/fu',
    [string] $Out = 'docs/follow-ups.md'
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Read-FrontMatter([string] $path) {
    $lines = Get-Content -LiteralPath $path -Encoding utf8
    if ($lines.Count -lt 2 -or $lines[0] -ne '---') { throw "fu-index: $path has no front matter" }
    $fm = @{}
    for ($i = 1; $i -lt $lines.Count -and $lines[$i] -ne '---'; $i++) {
        if ($lines[$i] -match '^([a-z]+):\s*(.*)$') { $fm[$Matches[1]] = $Matches[2].Trim() }
    }
    foreach ($key in 'id', 'title', 'status', 'kind') {
        if (-not $fm.ContainsKey($key) -or -not $fm[$key]) { throw "fu-index: $path has no '$key' in its front matter" }
    }
    $fm
}

if (-not (Test-Path -LiteralPath $Dir)) { throw "fu-index: no entry folder '$Dir' (run from the repo root)" }
$entries = Get-ChildItem -LiteralPath $Dir -Filter 'FU-*.md' -File |
    ForEach-Object { $fm = Read-FrontMatter $_.FullName; $fm['file'] = $_.Name; [pscustomobject]$fm } |
    Sort-Object { [int]($_.id -replace '\D', '') }

$cell = { param($s) ($s ?? '') -replace '\|', '\|' }
$outDir = Split-Path -Parent ([IO.Path]::GetFullPath($Out))
$rel = [IO.Path]::GetRelativePath($outDir, [IO.Path]::GetFullPath($Dir)) -replace '\\', '/'
$link = { param($e) "<a id=""$($e.id.ToLowerInvariant())""></a>[$($e.id)]($rel/$($e.file))" }

$open = @($entries | Where-Object { $_.status -like 'open*' })
$closed = @($entries | Where-Object { $_.status -notlike 'open*' })

$sb = [Text.StringBuilder]::new()
[void]$sb.AppendLine("<!-- GENERATED by fu-index.ps1 from $Dir/ — do not edit. Agents: never read this file; grep $Dir/ instead. -->")
[void]$sb.AppendLine('# Follow-ups')
[void]$sb.AppendLine()
[void]$sb.AppendLine("$($open.Count) open · $($closed.Count) done or dropped. Each entry is a file in [``$rel/``]($rel/); this page is regenerated whenever one changes.")
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Open')
[void]$sb.AppendLine()
if ($open.Count) {
    [void]$sb.AppendLine('| ID | Status | Kind | Revisit | Title |')
    [void]$sb.AppendLine('|----|--------|------|---------|-------|')
    foreach ($e in $open) {
        $revisit = if ($e.PSObject.Properties['revisit']) { $e.revisit } else { '' }
        if ($revisit.Length -gt 60) { $revisit = $revisit.Substring(0, 59).TrimEnd() + '…' }
        [void]$sb.AppendLine("| $(& $link $e) | $(& $cell $e.status) | $(& $cell $e.kind) | $(& $cell $revisit) | $(& $cell $e.title) |")
    }
} else { [void]$sb.AppendLine('None.') }
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Done / dropped')
[void]$sb.AppendLine()
if ($closed.Count) {
    [void]$sb.AppendLine('| ID | Status | Kind | Title |')
    [void]$sb.AppendLine('|----|--------|------|-------|')
    foreach ($e in $closed) {
        [void]$sb.AppendLine("| $(& $link $e) | $(& $cell $e.status) | $(& $cell $e.kind) | $(& $cell $e.title) |")
    }
} else { [void]$sb.AppendLine('None.') }

$text = $sb.ToString() -replace "`r`n", "`n"
$current = if (Test-Path -LiteralPath $Out) { [IO.File]::ReadAllText([IO.Path]::GetFullPath($Out)) } else { $null }
if ($current -ne $text) {
    [IO.File]::WriteAllText([IO.Path]::GetFullPath($Out), $text, [Text.UTF8Encoding]::new($false))
    Write-Host "fu-index: wrote $Out ($($open.Count) open, $($closed.Count) closed)"
} else {
    Write-Host "fu-index: $Out already current"
}
