#Requires -Version 7.0
# One-off: splits a single-file ledger (### FU-NNN: headings with - **Field:** bullets) into one file per entry
# with front matter, then regenerates the ledger path as the generated index (fu-index.ps1).
#   pwsh -NoProfile -File fu-migrate.ps1 [-Ledger docs/follow-ups.md] [-Dir docs/fu]
# Run from the repo root. Refuses to run if the entry folder already holds entries. Nothing is committed.
param(
    [string] $Ledger = 'docs/follow-ups.md',
    [string] $Dir = 'docs/fu'
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not (Test-Path -LiteralPath $Ledger)) { throw "fu-migrate: no ledger at $Ledger" }
$text = [IO.File]::ReadAllText([IO.Path]::GetFullPath($Ledger))
if ($text -match '^<!-- GENERATED by fu-index') { throw "fu-migrate: $Ledger is already a generated index" }
if ((Test-Path -LiteralPath $Dir) -and (Get-ChildItem -LiteralPath $Dir -Filter 'FU-*.md')) { throw "fu-migrate: $Dir already holds entries" }

$lines = $text -split "`r?`n"
$moved = 'Status', 'Kind', 'Origin', 'Areas'
$entries = [Collections.Generic.List[object]]::new()
$cur = $null
foreach ($line in $lines) {
    if ($line -match '^<a id="fu-\d+"></a>\s*$') { continue }
    if ($line -match '^###\s+(FU-\d+):\s*(.+?)\s*$') {
        $cur = [pscustomobject]@{ id = $Matches[1]; title = $Matches[2]; fields = @{}; body = [Collections.Generic.List[string]]::new() }
        $entries.Add($cur); continue
    }
    if ($line -match '^##\s') { $cur = $null; continue }
    if (-not $cur) { continue }
    if ($line -match '^- \*\*([A-Za-z ]+):\*\*\s*(.*)$' -and $Matches[1] -in $moved) { $cur.fields[$Matches[1]] = $Matches[2].Trim(); continue }
    $cur.body.Add($line)
}
if (-not $entries.Count) { throw "fu-migrate: no '### FU-NNN:' entries found in $Ledger" }
$dupes = $entries | Group-Object id | Where-Object Count -gt 1
if ($dupes) { throw "fu-migrate: duplicate ids: $($dupes.Name -join ', ')" }

# In-ledger links (#fu-012) become sibling-file links (FU-012.md).
$relink = { param($s) [regex]::Replace($s, '\]\(#fu-(\d+)\)', { param($m) "](FU-$($m.Groups[1].Value).md)" }) }
# Split a comma list, ignoring commas inside parentheses.
function Split-List([string] $s) {
    $items = [Collections.Generic.List[string]]::new(); $depth = 0; $buf = ''
    foreach ($ch in $s.ToCharArray()) {
        if ($ch -eq '(') { $depth++ } elseif ($ch -eq ')') { $depth-- }
        if ($ch -eq ',' -and $depth -eq 0) { $items.Add($buf.Trim()); $buf = '' } else { $buf += $ch }
    }
    if ($buf.Trim()) { $items.Add($buf.Trim()) }
    $items
}

New-Item -ItemType Directory -Force -Path $Dir | Out-Null
foreach ($e in $entries) {
    foreach ($f in 'Status', 'Kind') { if (-not $e.fields.ContainsKey($f)) { throw "fu-migrate: $($e.id) has no **${f}:**" } }
    while ($e.body.Count -and -not $e.body[0].Trim()) { $e.body.RemoveAt(0) }
    while ($e.body.Count -and -not $e.body[$e.body.Count - 1].Trim()) { $e.body.RemoveAt($e.body.Count - 1) }

    # Effective Revisit when: the latest "Revisit when → X — why" Update, else the field.
    $revisit = ''; $revisitIdx = -1
    for ($i = 0; $i -lt $e.body.Count; $i++) {
        if ($e.body[$i] -match '^- \*\*Revisit when:\*\*\s*(.*)$') { $revisit = $Matches[1]; $revisitIdx = $i }
    }
    $updated = $false
    foreach ($l in $e.body) {
        if ($l -match 'Revisit when →\s*(.+?)(\s+—\s+|$)') { $revisit = $Matches[1]; $updated = $true }
    }
    if ($revisitIdx -ge 0) {
        if ($updated) { $e.body[$revisitIdx] = $e.body[$revisitIdx] -replace '^- \*\*Revisit when:\*\*', '- **Revisit when (original):**' }
        else { $e.body.RemoveAt($revisitIdx) }
    }

    # files: backticked repo paths in Impacts that exist on disk (folders included).
    $files = [Collections.Generic.List[string]]::new()
    foreach ($l in $e.body) {
        if ($l -notmatch '^- \*\*Impacts:\*\*') { continue }
        foreach ($m in [regex]::Matches($l, '`([^`\s]+)`')) {
            $p = $m.Groups[1].Value.TrimEnd('/', ',', '.', ';')
            if ($p -match '[/\\]|\.\w+$' -and (Test-Path -LiteralPath $p) -and -not $files.Contains($p)) { $files.Add($p) }
        }
    }

    $areas = if ($e.fields.ContainsKey('Areas')) { (Split-List $e.fields['Areas']) -join ', ' } else { '' }
    $fm = @(
        '---'
        "id: $($e.id)"
        "title: $($e.title)"
        "status: $($e.fields['Status'])"
        "kind: $($e.fields['Kind'] -replace '`', '')"
        "areas: [$areas]"
        "files: [$($files -join ', ')]"
        "revisit: $(& $relink $revisit)"
        "origin: $($e.fields['Origin'])"
        '---'
        ''
    )
    $out = ($fm + ($e.body | ForEach-Object { & $relink $_ })) -join "`n"
    [IO.File]::WriteAllText([IO.Path]::GetFullPath((Join-Path $Dir "$($e.id).md")), "$out`n", [Text.UTF8Encoding]::new($false))
}
Write-Host "fu-migrate: wrote $($entries.Count) entries to $Dir"
& (Join-Path $PSScriptRoot 'fu-index.ps1') -Dir $Dir -Out $Ledger
